language: java

script: mvn -Drandomized.multiplier=10 -Dsolr.version=$SOLR_VERSION -Dlog.level=WARN clean verify

jdk:
  - openjdk7
env:
# see pom.xml for notes on previous versions
  - SOLR_VERSION=5.3.1

notifications:
  email:
    - dsmiley@apache.org
